# Generated by Django 4.0.1 on 2022-02-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='user',
        ),
    ]
